import { Process } from '@igrp/platform-process-management-types';

export const processes: Process[] = [
  // Sistema de Gestão (proj_1) processes
  {
    id: '1',
    key: 'process_1',
    projectId: 'proj_1',
    name: 'Processo de Gestão de Férias',
    description: 'Este processo automatiza o pedido e a aprovação de férias dos colaboradores.',
    version: '1.0',
    deploymentId: 'dep_1',
    deploymentTime: '2023-01-10T10:00:00Z',
    category: 'Recursos Humanos',
    thumbnail: 'https://cdn-icons-png.flaticon.com/512/3062/3062334.png',
  },
  {
    id: '2',
    key: 'process_2',
    projectId: 'proj_1',
    name: 'Processo de Aprovação de Despesas',
    description: 'Processo para aprovação de despesas corporativas.',
    version: '1.1',
    deploymentId: 'dep_2',
    deploymentTime: '2023-02-15T14:30:00Z',
    category: 'Financeiro',
    thumbnail: 'https://cdn-icons-png.flaticon.com/512/2621/2621864.png',
  },
  // Portal do Cliente (proj_2) processes
  {
    id: '3',
    key: 'process_3',
    projectId: 'proj_2',
    name: 'Processo de Atendimento ao Cliente',
    description: 'Processo para gestão de tickets de atendimento.',
    version: '2.0',
    deploymentId: 'dep_3',
    deploymentTime: '2023-03-20T09:00:00Z',
    category: 'Atendimento',
    thumbnail: 'https://cdn-icons-png.flaticon.com/512/3062/3062334.png',
  },
  {
    id: '4',
    key: 'process_4',
    projectId: 'proj_2',
    name: 'Processo de Feedback do Cliente',
    description: 'Coleta e análise de feedback dos clientes.',
    version: '1.0',
    deploymentId: 'dep_4',
    deploymentTime: '2023-04-10T11:00:00Z',
    category: 'Qualidade',
    thumbnail: 'https://cdn-icons-png.flaticon.com/512/2621/2621864.png',
  },
  // Sistema de Relatórios (proj_3) processes
  {
    id: '5',
    key: 'process_5',
    projectId: 'proj_3',
    name: 'Geração de Relatórios Financeiros',
    description: 'Processo automatizado para geração de relatórios financeiros.',
    version: '1.5',
    deploymentId: 'dep_5',
    deploymentTime: '2023-05-15T16:00:00Z',
    category: 'Relatórios',
    thumbnail: 'https://cdn-icons-png.flaticon.com/512/3062/3062334.png',
  },
  // Sistema de RH (proj_4) processes
  {
    id: '6',
    key: 'process_6',
    projectId: 'proj_4',
    name: 'Onboarding de Novo Colaborador',
    description: 'Processo para integração de novos colaboradores na empresa.',
    version: '2.0',
    deploymentId: 'dep_6',
    deploymentTime: '2023-06-20T09:00:00Z',
    category: 'Recursos Humanos',
    thumbnail: 'https://cdn-icons-png.flaticon.com/512/3062/3062334.png',
  },
  {
    id: '7',
    key: 'process_7',
    projectId: 'proj_4',
    name: 'Processo de Avaliação de Desempenho',
    description: 'Avaliação periódica de desempenho dos colaboradores.',
    version: '1.3',
    deploymentId: 'dep_7',
    deploymentTime: '2023-07-10T14:00:00Z',
    category: 'Recursos Humanos',
    thumbnail: 'https://cdn-icons-png.flaticon.com/512/2621/2621864.png',
  },
  // Portal de Vagas (proj_5) processes
  {
    id: '8',
    key: 'process_8',
    projectId: 'proj_5',
    name: 'Processo de Publicação de Vagas',
    description: 'Publicação e gestão de vagas de emprego.',
    version: '1.0',
    deploymentId: 'dep_8',
    deploymentTime: '2023-08-05T10:00:00Z',
    category: 'Recrutamento',
    thumbnail: 'https://cdn-icons-png.flaticon.com/512/3062/3062334.png',
  },
  {
    id: '9',
    key: 'process_9',
    projectId: 'proj_5',
    name: 'Processo de Seleção de Candidatos',
    description: 'Triagem e seleção de candidatos para vagas.',
    version: '1.2',
    deploymentId: 'dep_9',
    deploymentTime: '2023-08-20T15:30:00Z',
    category: 'Recrutamento',
    thumbnail: 'https://cdn-icons-png.flaticon.com/512/2621/2621864.png',
  }
];
