import { Task } from '@igrp/platform-process-management-types';

export const tasks: Task[] = [
  {
    id: 'task_1',
    name: 'Aprovar Pedido de Férias',
    description: 'Revisar e aprovar o pedido de férias do colaborador João Silva.',
    processInstanceId: 'pi_1',
    processDefinitionId: '1',
    taskDefinitionKey: 'approve_vacation',
    processName: 'Processo de Gestão de Férias',
    createdDate: '2023-06-01T10:00:00Z',
    dueDate: '2023-06-05T17:00:00Z',
    priority: 1,
    assignee: 'user_2',
    formKey: 'form_vacation_approval',
    status: 'ASSIGNED',
  },
  {
    id: 'task_2',
    name: 'Submeter Relatório de Despesas',
    description: 'Preencher e submeter o relatório de despesas da viagem a São Paulo.',
    processInstanceId: 'pi_2',
    processDefinitionId: '2',
    taskDefinitionKey: 'submit_expense_report',
    processName: 'Processo de Reembolso de Despesas',
    createdDate: '2023-06-02T11:30:00Z',
    priority: 2,
    assignee: 'user_1',
    formKey: 'form_expense_report',
    status: 'CREATED',
  },
  {
    id: 'task_3',
    name: 'Preparar Kit de Boas-Vindas',
    description: 'Montar o kit de boas-vindas para a nova colaboradora Maria Santos.',
    processInstanceId: 'pi_3',
    processDefinitionId: '3',
    taskDefinitionKey: 'prepare_welcome_kit',
    processName: 'Onboarding de Novo Colaborador',
    createdDate: '2023-06-03T09:00:00Z',
    assignee: 'user_3',
    status: 'ASSIGNED',
  },
];
